### ISSUE TITLE
mnu files is missing

### ISSUE THREAD

**Issue by CyGaNeo** [Benji667/LabVIEW_NPOI#10]
**Describe the bug**
LabVIEW searches for a mnu file when dropping a VI from the NPIO lib on a block diagram : controls_benjaminr_custom_controls.mnu

**To Reproduce**
1. install the package
2. Drop a NPIO VI on an empty block diagram

**Expected behavior**
No missing dependency

**Screenshots**
![image](https://user-images.githubusercontent.com/86322638/128094499-fdc9268e-2892-4ca9-985f-34b3447a54af.png)

**Environment (please complete the following information):**
 - Win10 x64
 - LabVIEW Version 2017
 - LabVIEW Bitness 32bit
 - Runtime? No

**Additional context**
None

**Comment by Benji667** [comment]
Hi CyGaNeo ,

Thanks for your feedback. This issue should has been fixed with the latest release (1.1.2). 

Feel free ton download and install it and keep me posted how thing goes.
