### ISSUE TITLE
Non functionnal builds

### ISSUE THREAD

**Issue by mathieu-reyrolle** [Benji667/LabVIEW_NPOI#13]
**Describe the bug**
I just build a very simple VI to build an executable and I've seen two issues related to build
1. If I do not uncheck **Remove unused members of project libraries** in Additional Exclusions, the executable cannot find the class coerrsponding to the file format (MS-Excel.lvclass for *.xlsx or *.xls, MS-Word for *.docx or *.doc). This lead to an error 7.
2. With this option unchecked, I get an error 1172. It seems that the direct dependencies are copied into data fodler, in build destination folder (NPOI.dll, NPOI.OOXML.dll), but three dependant assembly are missing (ICSharpCode.SharpZipLib.dll, NPOI.OpenXml4Net.dll, NPOI.OpenXmlFormats.dll)

**To Reproduce**
1. Open the attached project, review Main.vi (I inserted the code snippet found on the project home page on a blank VI, replaced the path control by a File Dialog, and add an Simple Error Handler after Close Document)
[Build Dependencies Issues.zip](https://github.com/Benji667/LabVIEW_NPOI/files/7188311/Build.Dependencies.Issues.zip)
2. Build **My Application** : it only point to Main.vi. Run the generated executable : you should get an error 7
3. Build **My Application (fix 1)**. In Additional Exclusion, **Remove unused members of project libraries** was unchecked. Run the generated executable: you should get an error 1172
4. Build **My application (fix 1 + fix 2)**. The three missing DLL (ICSharpCode.SharpZipLib.dll, NPOI.OpenXml4Net.dll, NPOI.OpenXmlFormats.dll) are explicitly referenced in the project, in order to force their copy into data forlder. The generated executable should run just fine.

**Expected behavior**
Getting a working build without build spec "trick"

**Screenshots**
![GetImage](https://user-images.githubusercontent.com/58079078/133851133-98f8e833-9f99-4bfe-a825-65a5da3df61b.png)

![GetImage (1)](https://user-images.githubusercontent.com/58079078/133851189-28eb6247-f65a-47a7-8d27-435e99d52def.png)

**Environment**
 - Target: Win 10
 - LabVIEW Version 2017
 - LabVIEW Bitness 32-bit
 - Runtime? Yes

**Additional context**
Issues first encountered when building a PPL with LabVIEW 2020, reproduced with a simple example project under LabVIEW 2017.

**Comment by Benji667** [comment]
Adding a VI that referred to each assembly should fix this issue.

**Comment by Benji667** [comment]
I added a VI into Document.lvclass that does referred NPOI assemblies that is called within the openDocument.vi
![refAssemblies](https://user-images.githubusercontent.com/25013486/135191335-7daaa504-8c0c-4c66-86a7-bf9081f3eea9.png)

**Comment by Benji667** [comment]
@mathieu-reyrolle could you try to build you example using the source from the [Build-Dependencies-Issue branch ](https://github.com/Benji667/LabVIEW_NPOI/tree/feature/Build-Dependencies-Issue)?

**Comment by mathieu-reyrolle** [comment]
Quick test here, with "ugly" relinkink to the source of the Build-Dependencies-Issue branch : build and run are OK.

I've seen the added VI for .Net assemblies reference. But I don't get how was addressed the child class referencing issue (used child class know only at run time). I probably missed something... but it works !

**Comment by Benji667** [comment]
The refAssemblies.vi allows to create static linkages that avoids managing Assemblies in the "Always Include" section of the AppBuilder. 
To address the child class referencing issue I, now, call openDocument parent method in both MS-Excel et MS-Word class. Here my understanding, LabVIEW will now include all VIs that calls refAssemblies.vi meaning both openDocument from MS-Excel and MS-Word class and voilà;
